# Generated by Django 5.0.6 on 2024-06-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
    ]
