# Generated by Django 5.0.6 on 2024-06-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coglivros', '0002_alter_livro_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
