# Generated by Django 5.0.6 on 2024-06-03 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coglivros', '0003_livro_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
