# Generated by Django 5.0.6 on 2024-06-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coglivros', '0004_livro_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
